# app.yaml
runtime: nodejs12
env: flex
handlers:
  # Serve all static files with urls ending with a file extension
  - url: /(.*\..+)$
    static_files: dist/spa/\1
    upload: dist/spa/(.*\..+)$
    # catch all handler to index.html
  - url: /.*
    static_files: dist/spa/index.html
    upload: dist/spa/index.html
# If you have one application, please use "default" for service
service: default
# VPC Network if you have one
#network:
#  name: default
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.5
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 15
