steps:
  - name: node
    entrypoint: npm
    args: ["install"]

  - name: quasar
    args: ["quasar", "build"]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: bash
    args:
      - "-c"
      - |
        cp app.yaml ./dist/spa #not sure if this is necessary
        gcloud app deploy
options:
  logging: CLOUD_LOGGING_ONLY
